version: '3.8'
services:
  app:
    image: php:8.3-fpm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on: [db]
  web:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on: [app]
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
